### PR TITLE
Intuitive login

### PR DESCRIPTION
**Pull request by Txu045**
Takes you directly to dashboard on login along with a toast welcoming the user.

### CODE REVIEW

**Comment by meganhng** [comment]
would we be able to also add something on the dashboard to make it more clear that the person is logged in? Maybe have their profile picture visible?

**Comment by Txu045** [comment]
After logging in:
image

Home index when logged in:
image

**Comment by meganhng** [comment]
> After logging in: image
> 
> Home index when logged in: image

Looks good! Can you push the commit up?

**Review by meganhng — APPROVED** [review]
lgtm

**Comment by Txu045** [comment]
Divider added between buttons and icon
image

**Pull request merged**
